sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.6.3
script:
  - export RAILS_ENV=test
  - bundle exec rake app:db:create app:db:setup
  - bundle exec rspec spec && bundle exec codeclimate-test-reporter
env:
  - DB=mysql
  - DB=sqlite
  - DB=postgresql
gemfile:
  - gemfiles/Gemfile.rails-6.0-stable
  - gemfiles/Gemfile.rails-5.2-stable
  - gemfiles/Gemfile.rails-5.1-stable
  - gemfiles/Gemfile.rails-5.0-stable
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-3.2-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: 2.2.7 # 2.2 is in security maintenace phase: https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
    - rvm: 2.4.1 # These 3 rails version don't seem to play well with ruby 2.4
      gemfile: gemfiles/Gemfile.rails-3.2-stable
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.0-stable
  include:
    - env: THREADSAFE=true DB=mysql
      gemfile: gemfiles/Gemfile.rails-3.2-stable
      rvm: 2.3.4
    - env: THREADSAFE=true DB=postgresql
      gemfile: gemfiles/Gemfile.rails-3.2-stable
      rvm: 2.3.4
    - env: THREADSAFE=true DB=sqlite
      gemfile: gemfiles/Gemfile.rails-3.2-stable
      rvm: 2.3.4
notifications:
    hipchat:
        rooms:
            - secure: "cVvKnySyhAuBtAqXKwxsMamfjkGe63OldAdP4eSNv6syr0BNcJirfDN6OsH1bzAbvCq/lEK1udLDzPrEsP0S51zBG2tGaeY7pXeBhHigBGFmC6wsAfMtPkDTyursm6f6Orl0LrMB4RPTNi6RFXdKDvTk430NBjh8YgKkZ7EzBtg="
addons:
    code_climate:
        repo_token: c209fccefc8ce2e54a4ba49867ab7762023ba326a836616eb36afe8016bd56bf
